/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proxy.h"

char *fetchpage_1_arg;

void
proxyserver_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	wd_in result_1;
	memset(&result_1,0,sizeof(result_1));

#ifndef	DEBUG
	clnt = clnt_create (host, ProxyServer, ProxyV1, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	retval_1=fetchpage_1(&fetchpage_1_arg, &result_1, clnt);
	printf("%s\n%u\n%u\n%d\n",result_1.data,result_1.size,result_1.len,retval_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host url\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	fetchpage_1_arg=argv[2];
	proxyserver_1 (host);
	exit (0);
}
