/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "proxy.h"

bool_t
xdr_wd_in (XDR *xdrs, wd_in *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->len))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->data, 300000))
		 return FALSE;
	return TRUE;
}
