./client localhost http://www.berkeley.edu/about/
./client localhost http://www.aad.berkeley.edu/
./client localhost http://registrar.berkeley.edu/CalendarDisp.aspx?terms=current
./client localhost http://academicservices.berkeley.edu/
./client localhost http://acads.chance.berkeley.edu/
./client localhost http://www.berkeley.edu/academics/dept/a.shtml
./client localhost http://afo.berkeley.edu/
./client localhost http://apo.chance.berkeley.edu/
./client localhost http://catalog.berkeley.edu/policies/
./client localhost http://academic-senate.berkeley.edu/
./client localhost http://academicservices.berkeley.edu/
./client localhost http://atdp.berkeley.edu/
./client localhost http://registrar.berkeley.edu/Registration/adddrop.html
./client localhost http://administration.berkeley.edu
./client localhost http://www.berkeley.edu/admin/committees.shtml
./client localhost http://www.bai.berkeley.edu/
./client localhost http://EthicsCompliance.berkeley.edu/ResponsibilitiesGuide/index.shtml
./client localhost http://www.grad.berkeley.edu/admissions/
./client localhost http://students.berkeley.edu/admissions/
./client localhost http://www.berkeley.edu/apply
./client localhost http://www.universityofcalifornia.edu/admissions/undergrad_adm/apply/apply_online.html
./client localhost http://ls-advise.berkeley.edu/
./client localhost http://airforcerotc.berkeley.edu/
./client localhost http://africam.berkeley.edu/
./client localhost http://africa.berkeley.edu/
./client localhost http://socrates.berkeley.edu/~aging/
./client localhost http://are.berkeley.edu/
./client localhost http://airforcerotc.berkeley.edu/
./client localhost http://airbears.berkeley.edu/
./client localhost http://alumni.berkeley.edu/
./client localhost http://www.berkeley.edu/alum/
./client localhost http://alumni.berkeley.edu/services/career_services
./client localhost http://www.alumni.berkeley.edu/Students/Scholarships_and_Awards/main.asp
./client localhost http://americancultures.berkeley.edu/
./client localhost http://teaching.berkeley.edu/ahi/
./client localhost http://www.grad.berkeley.edu/aigp/
./client localhost http://ls.berkeley.edu/ugis/as/
./client localhost http://ucbclassics.dreamhosters.com/ancgreek/
./client localhost http://ls.berkeley.edu/dept/ahma/
./client localhost http://www.acuc.berkeley.edu/
./client localhost http://anthropology.berkeley.edu/
./client localhost http://hearstmuseum.berkeley.edu/
./client localhost http://www.coe.berkeley.edu/AST/
./client localhost http://www.universityofcalifornia.edu/admissions/undergrad_adm/apply/apply_online.html
./client localhost http://www.berkeley.edu/apply
./client localhost http://arf.berkeley.edu/
./client localhost http://arch.ced.berkeley.edu/
./client localhost http://asrg.berkeley.edu/
./client localhost http://ls.berkeley.edu/dept/arthistory/
./client localhost http://www.bampfa.berkeley.edu/
./client localhost http://art.berkeley.edu/
./client localhost http://ls.berkeley.edu/?q=about-college/l-s-divisions/arts-humanities
./client localhost http://arts.berkeley.edu/
./client localhost http://ethnicstudies.berkeley.edu/as/
./client localhost http://ieas.berkeley.edu/gas/
./client localhost http://businessservices.berkeley.edu/procurement/assessment
./client localhost http://www.asuc.org/
./client localhost http://astro.berkeley.edu/
./client localhost http://www.asuc.org/
./client localhost http://asuc.berkeley.edu/
./client localhost http://www.bkstr.com/Home/10001-10433-1?demoKey=d
./client localhost http://www.ocf.berkeley.edu/~superb/
./client localhost http://asc.berkeley.edu/
./client localhost http://www.audit.berkeley.edu/
./client localhost http://ear.berkeley.edu/
./client localhost http://www.berkeley.edu/about/honors.shtml
./client localhost http://awards.berkeley.edu
./client localhost http://www.berkeley.edu/academics/dept/a.shtml
./client localhost http://www.berkeley.edu/a-z/a.shtml
./client localhost http://opa.berkeley.edu/AcademicCalendar/calendardisp.aspx?terms=current
./client localhost http://events.berkeley.edu/
./client localhost http://catalog.berkeley.edu/
./client localhost http://schedule.berkeley.edu/
./client localhost http://summer.berkeley.edu/
./client localhost http://bearfacts.berkeley.edu/
./client localhost http://internationaloffice.berkeley.edu/
./client localhost http://www.berkeley.edu/work/jobs.shtml
./client localhost http://career.berkeley.edu/
./client localhost http://diversity.berkeley.edu/
./client localhost http://www.lib.berkeley.edu/
./client localhost http://www.mip.berkeley.edu/mip/collections/collections.html
./client localhost http://www.berkeley.edu/admin/compute.shtml
./client localhost http://blu.berkeley.edu
./client localhost http://ucberkeley.bkstr.com/
./client localhost http://calmarketplace.berkeley.edu/
./client localhost http://calbears.berkeley.edu/
./client localhost http://uhs.berkeley.edu/
./client localhost http://oep.berkeley.edu/
./client localhost http://www.berkeley.edu/academics/dept/a.shtml
./client localhost http://www.berkeley.edu/a-z/a.shtml
./client localhost http://events.berkeley.edu/
./client localhost http://catalog.berkeley.edu/
./client localhost http://schedule.berkeley.edu/
./client localhost http://summer.berkeley.edu/
./client localhost http://bearfacts.berkeley.edu/
./client localhost http://internationaloffice.berkeley.edu/
./client localhost http://www.berkeley.edu/work/jobs.shtml
./client localhost http://career.berkeley.edu/
./client localhost http://diversity.berkeley.edu/
./client localhost http://www.lib.berkeley.edu/
./client localhost http://www.mip.berkeley.edu/mip/collections/collections.html
./client localhost http://www.berkeley.edu/admin/compute.shtml
./client localhost http://blu.berkeley.edu
./client localhost http://ucberkeley.bkstr.com/
./client localhost http://calmarketplace.berkeley.edu/
./client localhost http://calbears.berkeley.edu/
./client localhost http://uhs.berkeley.edu/
./client localhost http://oep.berkeley.edu/
./client localhost http://www.urel.berkeley.edu/children/
./client localhost http://www.uhs.berkeley.edu/
./client localhost http://education.berkeley.edu
./client localhost http://www.berkeley.edu/teach/res.shtml
./client localhost http://tebtunis.berkeley.edu/
./client localhost http://tpo.berkeley.edu
./client localhost http://technology.berkeley.edu/services/
./client localhost http://technology.berkeley.edu/
./client localhost http://ls.berkeley.edu/?q=about-college/l-s-divisions/mathematical-physical-sciences/diversity/bep
./client localhost http://international.berkeley.edu
./client localhost http://ls.berkeley.edu/dept/theater/
./client localhost http://themeprograms.berkeley.edu
./client localhost http://astron.berkeley.edu/tac/
./client localhost http://tickets.berkeley.edu
./client localhost http://calbears.cstv.com/tickets/cal-tickets.html
./client localhost http://tiencenter.berkeley.edu/
./client localhost http://ccac.berkeley.edu
./client localhost http://www.berkeley.edu/tour/
./client localhost http://www.berkeley.edu/visitors/
./client localhost http://townsendcenter.berkeley.edu/
./client localhost http://nst.berkeley.edu/
./client localhost http://ombo.berkeley.edu/
./client localhost http://hrweb.berkeley.edu/learning/computer-classes/calpact
./client localhost http://registrar.berkeley.edu/Records/transdipl.html
./client localhost http://www.universityofcalifornia.edu/admissions/undergrad_adm/paths_to_adm/transfer.html
./client localhost http://www.uga.berkeley.edu/admissions/transfer.asp
./client localhost http://trsp.berkeley.edu
./client localhost http://pt.berkeley.edu/around/transit/routes
./client localhost http://www.uctc.net/
./client localhost http://www.its.berkeley.edu/
./client localhost http://controller.berkeley.edu/travel/
./client localhost http://crg.berkeley.edu/
./client localhost http://ucrc.berkeley.edu
./client localhost http://espm.berkeley.edu/gradprograms/grad_programs_msr.php
./client localhost http://reentry.berkeley.edu/
./client localhost http://landscape.ced.berkeley.edu/~delta/
./client localhost http://groups.haas.berkeley.edu/realestate/
./client localhost http://www.cp.berkeley.edu/reso/homepg.htm
./client localhost http://controller.berkeley.edu/recharge/
./client localhost http://www.recsports.berkeley.edu/
./client localhost http://www.recsports.berkeley.edu/
./client localhost http://www.oski.org/
./client localhost http://www.ocf.berkeley.edu/~recycle/
./client localhost http://redwood.berkeley.edu/
./client localhost http://registrar.berkeley.edu/
./client localhost http://rpgp.berkeley.edu/
./client localhost http://ls.berkeley.edu/ugis/religiousstudies/
./client localhost http://www.berkeley.edu/research/
./client localhost http://rac.berkeley.edu
./client localhost http://research.chance.berkeley.edu/main.cfm?id=7
./client localhost http://research.berkeley.edu/urap/
./client localhost http://res.berkeley.edu/res/
./client localhost http://research.chance.berkeley.edu/main.cfm?id=8
./client localhost http://iir.berkeley.edu/
./client localhost http://www.ucop.edu/research/policies/welcome.html
./client localhost http://research.chance.berkeley.edu/main.cfm?id=4
./client localhost http://research.chance.berkeley.edu/main.cfm?id=4
./client localhost http://vcresearch.berkeley.edu/
./client localhost http://www.housing.berkeley.edu/livingatcal/uchousing.html
./client localhost http://rts.berkeley.edu/
./client localhost http://www.housing.berkeley.edu/
./client localhost http://www.rescomp.berkeley.edu/
./client localhost http://caldining.berkeley.edu/residence_dining.html
./client localhost http://resource.berkeley.edu
./client localhost http://calparents.berkeley.edu/guide/
./client localhost http://www-RNC.lbl.gov/Restaurants/
./client localhost http://caldining.berkeley.edu/campus_restaurants.html
./client localhost http://thecenter.berkeley.edu/
./client localhost http://rhetoric.berkeley.edu/
./client localhost http://rfs.berkeley.edu
./client localhost http://EthicsCompliance.berkeley.edu/RiskServices/index.shtml
./client localhost http://lib.berkeley.edu/WRCA/restoration/
./client localhost http://www.law.berkeley.edu/robbins/
./client localhost http://www.law.berkeley.edu/centers/burch/
./client localhost http://cio.chance.berkeley.edu/chancellor/homepage.html
./client localhost http://robotics.eecs.berkeley.edu/wiki/pmwiki/pmwiki.php
./client localhost http://armyrotc.com/edu/univcaberkeley/
./client localhost http://navyrotc.berkeley.edu/
